### ISSUE TITLE
Feature properties and data maps as Map<String, dynamic> instead of Map<String, Object?>

### ISSUE THREAD

**Issue by navispatial** [navibyte/geospatial#147]
Using `Map<String, dynamic>` is "Dart standard way" to represent decoded JSON Objects.

However when "stong mode" was enabled on analysis options, this was had some issues (or required some extra type code). But when using following rules as described in #148 these issue are not valid anymore:

```yaml
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
```

So use the more standard way or `Map<String, dynamic>` for Feature properties and similar data maps (JSON Object) fields.
